import Foundation
import SwizzleCore

/// Emits `SQLTable` declarations from a live schema.
///
/// ## Why this exists
///
/// Table declarations are hand-written today, and the query builder's own
/// documentation admits the consequence: `varchar("email", 255)` records a type
/// that nothing verifies, so the declaration and the migration can drift apart
/// silently. Generating them from what the database actually reports closes that
/// — the SQL type stops being a comment and becomes a fact.
///
/// It also needs no query analysis at all, only the `SchemaIntrospector` every
/// engine already implements, which is why it lands before the harder half.
public struct SchemaEmitter: Sendable {
    /// What to call the generated declarations, and what to import.
    public struct Options: Sendable {
        public var accessLevel: String
        public var imports: [String]
        /// Which engine the schema was read from.
        ///
        /// Needed because the same type *name* means different widths: `INTEGER`
        /// is 32-bit on MySQL and Postgres and **64-bit** on SQLite, where it is
        /// also the rowid's type. Emitting `Int32` there would truncate every id
        /// past two billion.
        public var dialect: String

        public init(
            accessLevel: String = "public",
            imports: [String] = ["SwizzleCore", "SwizzleQuery"],
            dialect: String = ""
        ) {
            self.accessLevel = accessLevel
            self.imports = imports
            self.dialect = dialect
        }
    }

    let options: Options

    public init(options: Options = Options()) {
        self.options = options
    }

    public func emit(_ schema: DatabaseSchema) -> String {
        var out = Self.header
        for name in options.imports.sorted() { out += "import \(name)\n" }
        out += "\n"

        // Sorted so regeneration is byte-stable — the lockfile and `--verify`
        // both depend on the output not moving around.
        for table in schema.tables.sorted(by: { $0.name < $1.name }) {
            out += emit(table)
            out += "\n"
        }
        return out
    }

    func emit(_ table: TableSchema) -> String {
        let type = SwiftNames.typeName(table.name)
        var out = """
        /// `\(table.name)`, generated from the live schema.
        \(options.accessLevel) struct \(type): SQLTable {
            \(options.accessLevel) static let tableName = "\(table.name)"
            \(options.accessLevel) var tableAlias: String?

            \(options.accessLevel) init(tableAlias: String? = nil) {
                self.tableAlias = tableAlias
            }


        """

        for column in table.columns {
            let member = SwiftNames.memberName(column.name)
            let declaration = ColumnTypeName.parse(column.type, dialect: options.dialect)
            // An auto-increment column is never null in a result, whatever the
            // schema says about inserting into it. SQLite is the reason this
            // matters: `id INTEGER PRIMARY KEY` is the rowid alias, and inserting
            // NULL is legal and means "assign one" — so the schema truthfully
            // reports it nullable, and taking that at face value would make every
            // primary key an optional.
            let isOptional = column.isNullable && !column.isAutoIncrement
            let swiftType = declaration.swiftType.sourceText + (isOptional ? "?" : "")
            out += "    \(options.accessLevel) var \(member): SQLColumn<\(swiftType)> "
            out += "{ \(declaration.constructorCall(named: column.name)) }\n"
        }

        out += "}\n"
        return out
    }

    /// Generated files say so, and say not to edit them.
    static let header = """
        // Generated by swizzle. Do not edit.
        //
        // Regenerate with `swizzle generate schema`. Edits are lost on the next run;
        // change the migration instead, which is the source of truth this was read from.


        """
}

/// A column type as the server rendered it, taken apart.
///
/// The three engines describe types in their own words — `varchar(255)`,
/// `bigint unsigned`, `INTEGER`, `numeric(10,2)`, `character varying` — but they
/// describe them in the *same shape*: a name, optional parenthesised arguments,
/// and optional trailing words. Splitting on that shape is enough to pick a
/// constructor, and it needs no per-engine table.
struct ColumnTypeName {
    var base: String
    var arguments: [Int]
    var isUnsigned: Bool
    var dialect: String

    static func parse(_ raw: String, dialect: String = "") -> ColumnTypeName {
        let lowered = raw.lowercased()
        let isUnsigned = lowered.contains("unsigned")

        var base = lowered
        var arguments: [Int] = []
        if let open = lowered.firstIndex(of: "("), let close = lowered.firstIndex(of: ")"), open < close {
            base = String(lowered[lowered.startIndex..<open])
            arguments = lowered[lowered.index(after: open)..<close]
                .split(separator: ",")
                .compactMap { Int($0.trimmingCharacters(in: .whitespaces)) }
        }
        base = base
            .replacingOccurrences(of: "unsigned", with: "")
            .replacingOccurrences(of: "zerofill", with: "")
            .trimmingCharacters(in: .whitespaces)

        return ColumnTypeName(
            base: base, arguments: arguments, isUnsigned: isUnsigned, dialect: dialect
        )
    }

    /// The `SQLColumn` constructor call, matching the SQL type as closely as the
    /// constructors allow — which is the whole point of them.
    func constructorCall(named column: String) -> String {
        let name = "\"\(column)\""
        switch base {
        case "tinyint": return "tinyInt(\(name))"
        case "smallint", "int2": return "smallInt(\(name))"
        case "mediumint", "int", "integer", "int4": return "int(\(name))"
        case "bigint", "int8": return "bigInt(\(name))"
        case "serial", "bigserial", "smallserial": return "serial(\(name))"

        case "decimal", "dec": return "decimal(\(name), \(argument(0, 10)), \(argument(1, 0)))"
        case "numeric": return "numeric(\(name), \(argument(0, 10)), \(argument(1, 0)))"
        case "real", "float4": return "real(\(name))"
        case "double", "double precision", "float", "float8": return "double(\(name))"

        case "char", "character", "bpchar": return "char(\(name), \(argument(0, 1)))"
        case "varchar", "character varying", "varchar2":
            return "varchar(\(name), \(argument(0, 255)))"
        case "text", "tinytext", "mediumtext", "longtext", "clob": return "text(\(name))"

        case "binary": return "binary(\(name), \(argument(0, 1)))"
        case "varbinary": return "varbinary(\(name), \(argument(0, 255)))"
        case "blob", "tinyblob", "mediumblob", "longblob": return "blob(\(name))"
        case "bytea": return "bytea(\(name))"

        case "bool", "boolean": return "boolean(\(name))"

        case "date": return "date(\(name))"
        case "time", "time without time zone": return "time(\(name))"
        case "datetime": return "datetime(\(name))"
        case "timestamp", "timestamp without time zone": return "timestamp(\(name))"
        case "timestamptz", "timestamp with time zone": return "timestamptz(\(name))"

        case "json": return "json(\(name))"
        case "jsonb": return "jsonb(\(name))"
        case "uuid": return "uuid(\(name))"
        case "enum": return "`enum`(\(name))"

        default:
            // An engine-specific type nothing here models — a Postgres domain, a
            // geometry, an extension type. `column(_:)` keeps it usable and keeps
            // its real name visible, rather than guessing at a constructor.
            return "column(\(name))"
        }
    }

    func argument(_ index: Int, _ fallback: Int) -> Int {
        index < arguments.count ? arguments[index] : fallback
    }

    var isSQLite: Bool { dialect == "sqlite" }

    /// The Swift type the column decodes into.
    var swiftType: SwiftType {
        switch base {
        case "tinyint" where arguments.first == 1, "bool", "boolean": return .bool
        case "tinyint", "smallint", "int2": return isSQLite ? .int64 : .int16
        case "mediumint", "int", "integer", "int4", "serial", "smallserial":
            // SQLite's INTEGER is 64-bit — it is the rowid's own type — while
            // everyone else's is 32.
            return isSQLite ? .int64 : .int32
        // An unsigned 64-bit value does not fit `Int64`, and the driver already
        // hands those over as text rather than wrapping. `UInt64` accepts both.
        case "bigint", "int8", "bigserial": return isUnsigned ? .uint64 : .int64

        // Exact numerics stay text on every engine.
        case "decimal", "dec", "numeric": return .decimalString

        case "real", "float4": return .float
        case "double", "double precision", "float", "float8": return .double

        case "char", "character", "bpchar", "varchar", "character varying", "varchar2",
             "text", "tinytext", "mediumtext", "longtext", "clob", "enum":
            return .string

        case "binary", "varbinary", "blob", "tinyblob", "mediumblob", "longblob", "bytea":
            return .bytes

        case "date", "time", "time without time zone", "datetime",
             "timestamp", "timestamp without time zone",
             "timestamptz", "timestamp with time zone":
            return .date

        case "json", "jsonb": return .json
        case "uuid": return .uuid

        default: return .dynamic
        }
    }
}
