private let hexDigits: [Character] = Array("0123456789ABCDEF")

/// Renders SQL IR into dialect-specific text plus an ordered binding list.
///
/// Generic over the dialect so placeholder style ($1 vs ?) and identifier quoting
/// ("" vs ``) are static-dispatched and inlinable — no per-node branch on dialect.
public struct SQLRenderer<D: SQLDialect>: Sendable {
    public private(set) var sql: String = ""
    public private(set) var bindings: [SQLValue] = []

    /// When set, `bind` writes the value **into** the SQL as a literal instead of
    /// emitting a placeholder. Only `debugSQL` turns this on: the result is for
    /// reading and for pasting into a client by hand, never for execution.
    public let inlineBindings: Bool

    /// How many bindings were written into a position the server will never read
    /// as a parameter — inside a comment, or inside a string literal.
    ///
    /// Detected rather than documented. Interpolating a value into a comment is
    /// the one way a fragment can go wrong that the type system cannot see:
    /// `\(7)` writes a placeholder the server ignores while the value is still
    /// sent, so the counts desync and the driver reports *"statement expects 1
    /// parameters, got 2"* — an error with no hint about which interpolation
    /// caused it. Counting them here turns that into an actionable one.
    public private(set) var deadBindings = 0

    /// Lexer state, advanced only through text that came from a **fragment**.
    ///
    /// Everything else the renderer writes is generated by us and cannot contain
    /// an unterminated string or a comment, so the scan costs nothing on a query
    /// that uses no raw SQL.
    private var fragmentState = FragmentScanState.normal

    private enum FragmentScanState {
        case normal, single, double, backtick, lineComment, blockComment
    }

    public init(reservingCapacity: Int = 512, inlineBindings: Bool = false) {
        self.inlineBindings = inlineBindings
        sql.reserveCapacity(reservingCapacity)
    }

    /// Advances the lexer through verbatim fragment text.
    private mutating func scanFragmentText(_ text: String) {
        var iterator = text.makeIterator()
        var pending: Character? = nil
        while let character = pending ?? iterator.next() {
            pending = nil
            switch fragmentState {
            case .normal:
                switch character {
                case "'": fragmentState = .single
                case "\"": fragmentState = .double
                case "`": fragmentState = .backtick
                case "-":
                    if let next = iterator.next() {
                        if next == "-" { fragmentState = .lineComment } else { pending = next }
                    }
                case "/":
                    if let next = iterator.next() {
                        if next == "*" { fragmentState = .blockComment } else { pending = next }
                    }
                default: break
                }
            case .single where character == "'": fragmentState = .normal
            case .double where character == "\"": fragmentState = .normal
            case .backtick where character == "`": fragmentState = .normal
            case .lineComment where character == "\n": fragmentState = .normal
            case .blockComment where character == "*":
                if let next = iterator.next() {
                    if next == "/" { fragmentState = .normal } else { pending = next }
                }
            default: break
            }
        }
    }

    public mutating func write(_ s: String) { sql.append(s) }

    public mutating func identifier(_ name: String) {
        D.writeIdentifier(name, into: &sql)
    }

    public mutating func bind(_ value: SQLValue) {
        if fragmentState != .normal { deadBindings += 1 }
        guard !inlineBindings else {
            writeLiteral(value)
            // Still recorded, so `debugSQL` and `build()` agree on how many
            // values a statement carries even though only one of them emits
            // placeholders.
            bindings.append(value)
            return
        }
        D.writePlaceholder(index: bindings.count, into: &sql)
        bindings.append(value)
    }

    /// Formats a value as SQL source text.
    ///
    /// Two callers: `inlineBindings` for `debugSQL`, and `.literal` for a value
    /// deliberately written into the statement because the position will not take
    /// a parameter.
    mutating func writeLiteral(_ value: SQLValue) {
        switch value {
        case .null:
            sql.append("NULL")
        case .bool(let flag):
            sql.append(flag ? "TRUE" : "FALSE")
        case .int(let number):
            sql.append(String(number))
        case .double(let number):
            // Neither infinity nor NaN has a portable literal spelling, so they
            // are quoted rather than emitted bare: wrong to execute, but this
            // string was never for executing, and it reads as what it is.
            sql.append(number.isFinite ? String(number) : "'\(number)'")
        case .text(let string):
            sql.append("'")
            for character in string {
                // Doubling the quote is standard. Doubling the backslash is not,
                // but MySQL and MariaDB treat it as an escape unless
                // NO_BACKSLASH_ESCAPES is set — and the identifier quote is the
                // only dialect signal available here.
                if character == "'" { sql.append("''") }
                else if character == "\\" && D.identifierQuote == "`" { sql.append("\\\\") }
                else { sql.append(character) }
            }
            sql.append("'")
        case .blob(let bytes):
            sql.append("X'")
            for byte in bytes {
                sql.append(hexDigits[Int(byte >> 4)])
                sql.append(hexDigits[Int(byte & 0x0F)])
            }
            sql.append("'")
        }
    }

    public mutating func render(_ node: SQLNode) {
        switch node {
        case .column(let qualifier, let name):
            if let qualifier { identifier(qualifier); sql.append(".") }
            identifier(name)
        case .bind(let value):
            bind(value)
        case .raw(let text):
            scanFragmentText(text)
            sql.append(text)
        case .binary(let lhs, let op, let rhs):
            render(lhs); sql.append(" "); sql.append(op); sql.append(" "); render(rhs)
        case .prefix(let op, let operand):
            sql.append(op); sql.append(" "); render(operand)
        case .postfix(let operand, let op):
            render(operand); sql.append(" "); sql.append(op)
        case .function(let name, let args):
            sql.append(name); sql.append("(")
            renderCommaSeparated(args)
            sql.append(")")
        case .list(let items):
            sql.append("(")
            renderCommaSeparated(items)
            sql.append(")")
        case .group(let inner):
            sql.append("("); render(inner); sql.append(")")
        case .aliased(let inner, let alias):
            render(inner); sql.append(" AS "); identifier(alias)
        case .star(let qualifier):
            if let qualifier { identifier(qualifier); sql.append(".") }
            sql.append("*")
        case .selectSubquery(let core):
            sql.append("("); renderSelect(core); sql.append(")")
        case .identifier(let name):
            identifier(name)
        case .literal(let value):
            // Escaped, but written into the statement rather than bound — so it
            // is part of the prepared-statement cache key, which is the cost of
            // using it where a parameter will not go.
            writeLiteral(value)
        case .fragment(let parts):
            // No separator: the literal text between interpolations is itself a
            // `.raw` part, so the fragment already carries its own spacing.
            for part in parts { render(part) }
        case .excluded(let column):
            sql.append("EXCLUDED.")
            identifier(column)
        case .valuesOf(let column):
            sql.append("VALUES(")
            identifier(column)
            sql.append(")")
        }
    }

    private mutating func renderCommaSeparated(_ nodes: [SQLNode]) {
        for (i, node) in nodes.enumerated() {
            if i > 0 { sql.append(", ") }
            render(node)
        }
    }

    private mutating func renderOrderTerms(_ terms: [SQLOrderTerm]) {
        for (i, term) in terms.enumerated() {
            if i > 0 { sql.append(", ") }
            render(term.node)
            if term.descending { sql.append(" DESC") }
            if let nulls = term.nulls {
                sql.append(nulls == .first ? " NULLS FIRST" : " NULLS LAST")
            }
        }
    }

    private mutating func renderConjunction(_ nodes: [SQLNode]) {
        for (i, node) in nodes.enumerated() {
            if i > 0 { sql.append(" AND ") }
            render(node)
        }
    }

    public mutating func renderSource(_ source: SQLSource) {
        switch source {
        case .table(let schema, let name, let alias):
            if let schema { identifier(schema); sql.append(".") }
            identifier(name)
            if let alias { sql.append(" AS "); identifier(alias) }
        case .subquery(let core, let alias):
            sql.append("("); renderSelect(core); sql.append(") AS "); identifier(alias)
        case .fragment(let node, let alias):
            render(node)
            if let alias { sql.append(" AS "); identifier(alias) }
        }
    }

    public mutating func renderSelect(_ core: SQLSelectCore) {
        renderCTEs(core.ctes)
        renderSelectBody(core)
        // Set operations bind looser than everything above, so they come after
        // this query's own ORDER BY/LIMIT — which is why they are rendered here
        // rather than folded into the body.
        for operation in core.setOperations {
            sql.append(" ")
            sql.append(operation.kind.rawValue)
            sql.append(" ")
            renderSelectBody(operation.body)
        }
        // Locking binds to the whole statement and follows LIMIT/OFFSET on every
        // engine that has it, so it renders out here rather than in the body.
        if let locking = core.locking {
            sql.append(" ")
            sql.append(locking.strength.rawValue)
            if locking.wait != .wait {
                sql.append(" ")
                sql.append(locking.wait.rawValue)
            }
        }
        renderTrailing(core.trailing)
    }

    /// Writes verbatim fragments after everything else.
    ///
    /// One space in front of each, because a caller writing `FOR UPDATE` should
    /// not have to remember whether the clause before it left one.
    public mutating func renderTrailing(_ nodes: [SQLNode]) {
        for node in nodes {
            sql.append(" ")
            render(node)
        }
    }

    /// `WITH a AS (…), b AS (…)`.
    ///
    /// `RECURSIVE` is a property of the clause, not of one binding: SQL puts the
    /// keyword once after `WITH`, so any recursive binding makes the whole clause
    /// recursive. Postgres requires the keyword when it applies; MySQL 8 and
    /// SQLite accept it either way.
    private mutating func renderCTEs(_ ctes: [SQLCommonTableExpression]) {
        guard !ctes.isEmpty else { return }
        sql.append("WITH ")
        if ctes.contains(where: \.isRecursive) { sql.append("RECURSIVE ") }
        for (index, cte) in ctes.enumerated() {
            if index > 0 { sql.append(", ") }
            identifier(cte.name)
            if !cte.columns.isEmpty {
                sql.append(" (")
                for (columnIndex, column) in cte.columns.enumerated() {
                    if columnIndex > 0 { sql.append(", ") }
                    identifier(column)
                }
                sql.append(")")
            }
            sql.append(" AS (")
            renderSelect(cte.body)
            sql.append(")")
        }
        sql.append(" ")
    }

    private mutating func renderSelectBody(_ core: SQLSelectCore) {
        sql.append("SELECT ")
        if !core.distinctOn.isEmpty {
            sql.append("DISTINCT ON (")
            renderCommaSeparated(core.distinctOn)
            sql.append(") ")
        } else if core.isDistinct {
            sql.append("DISTINCT ")
        }

        if core.projection.isEmpty {
            sql.append("*")
        } else {
            renderCommaSeparated(core.projection)
        }

        if let from = core.from {
            sql.append(" FROM ")
            renderSource(from)
        }

        for join in core.joins {
            sql.append(" ")
            sql.append(join.kind.rawValue)
            sql.append(" ")
            if join.isLateral { sql.append("LATERAL ") }
            renderSource(join.source)
            if let on = join.on {
                sql.append(" ON ")
                render(on)
            }
        }

        if !core.predicates.isEmpty {
            sql.append(" WHERE ")
            renderConjunction(core.predicates)
        }

        if !core.groupBy.isEmpty {
            sql.append(" GROUP BY ")
            renderCommaSeparated(core.groupBy)
        }

        if !core.having.isEmpty {
            sql.append(" HAVING ")
            renderConjunction(core.having)
        }

        if !core.orderBy.isEmpty {
            sql.append(" ORDER BY ")
            renderOrderTerms(core.orderBy)
        }

        // LIMIT/OFFSET are bound, not interpolated — keeps the prepared-statement
        // cache key stable across pagination, which is the whole point of caching.
        if let limit = core.limit {
            sql.append(" LIMIT ")
            bind(.int(Int64(limit)))
        }
        if let offset = core.offset {
            sql.append(" OFFSET ")
            bind(.int(Int64(offset)))
        }
    }
}

// MARK: - INSERT

/// Dialect-neutral INSERT description, so the renderer stays in `SwizzleCore`
/// while the typed, capability-gated builder lives in `SwizzleQuery`.
public struct SQLInsertCore: Sendable {
    public enum ConflictAction: Sendable {
        case nothing
        case update([SQLAssignment])
    }

    public var table: String
    public var columns: [String] = []
    public var rows: [[SQLValue]] = []
    /// When set, the rows come from a `SELECT` instead of a `VALUES` list.
    public var selectSource: SQLSelectCore?
    public var trailing: [SQLNode] = []
    public var ignoreDuplicates = false
    public var conflictTargets: [String] = []
    public var conflictAction: ConflictAction?
    public var duplicateKeyUpdates: [SQLAssignment] = []
    public var returning: [SQLNode] = []

    public init(table: String) { self.table = table }
}

extension SQLRenderer {
    /// Renders an INSERT.
    ///
    /// The conflict clauses are mutually exclusive *by dialect*, not by runtime
    /// check: `onConflict` only exists on `SupportsOnConflict` and
    /// `onDuplicateKeyUpdate` only on `SupportsOnDuplicateKeyUpdate`, so a core
    /// carrying both could only be built by hand. Rendering both would produce
    /// nonsense, so the Postgres form wins and the MySQL form is skipped —
    /// unreachable through the typed builder either way.
    public mutating func renderInsert(_ core: SQLInsertCore) {
        write("INSERT ")
        // MySQL and SQLite spell "ignore duplicates" differently, and this is
        // the one place the two must not be conflated: `INSERT OR IGNORE` is a
        // syntax error on MySQL and `INSERT IGNORE` is one on SQLite.
        if core.ignoreDuplicates {
            write(D.dialectName == "sqlite" ? "OR IGNORE " : "IGNORE ")
        }
        write("INTO ")
        identifier(core.table)

        if !core.columns.isEmpty {
            write(" (")
            for (index, column) in core.columns.enumerated() {
                if index > 0 { write(", ") }
                identifier(column)
            }
            write(")")
        }

        if let source = core.selectSource {
            // `INSERT … SELECT` — no VALUES keyword, the select *is* the source.
            write(" ")
            renderSelect(source)
        } else {
            write(" VALUES ")
            for (rowIndex, row) in core.rows.enumerated() {
                if rowIndex > 0 { write(", ") }
                write("(")
                for (valueIndex, value) in row.enumerated() {
                    if valueIndex > 0 { write(", ") }
                    bind(value)
                }
                write(")")
            }
        }

        if !core.conflictTargets.isEmpty || core.conflictAction != nil {
            write(" ON CONFLICT")
            if !core.conflictTargets.isEmpty {
                write(" (")
                for (index, target) in core.conflictTargets.enumerated() {
                    if index > 0 { write(", ") }
                    identifier(target)
                }
                write(")")
            }
            switch core.conflictAction {
            case .nothing, nil:
                write(" DO NOTHING")
            case .update(let assignments):
                write(" DO UPDATE SET ")
                renderAssignments(assignments)
            }
        } else if !core.duplicateKeyUpdates.isEmpty {
            write(" ON DUPLICATE KEY UPDATE ")
            renderAssignments(core.duplicateKeyUpdates)
        }

        if !core.returning.isEmpty {
            write(" RETURNING ")
            for (index, node) in core.returning.enumerated() {
                if index > 0 { write(", ") }
                render(node)
            }
        }
        renderTrailing(core.trailing)
    }

    private mutating func renderAssignments(_ assignments: [SQLAssignment]) {
        for (index, assignment) in assignments.enumerated() {
            if index > 0 { write(", ") }
            // The target loses its qualifier. `UPDATE users SET users.name = …`
            // is legal MySQL and a syntax error in Postgres, and the table is
            // never ambiguous on the left of a SET, so the bare name is the only
            // form that works everywhere.
            if case .column(_, let name) = assignment.target {
                identifier(name)
            } else {
                render(assignment.target)
            }
            write(" = ")
            render(assignment.value)
        }
    }

    private mutating func renderReturning(_ nodes: [SQLNode]) {
        guard !nodes.isEmpty else { return }
        write(" RETURNING ")
        renderCommaSeparated(nodes)
    }

    /// `ORDER BY` / `LIMIT` on a write. Only MySQL and MariaDB reach this — the
    /// builder gates it behind `SupportsWriteLimit`.
    private mutating func renderWriteTail(_ orderBy: [SQLOrderTerm], _ limit: Int?) {
        if !orderBy.isEmpty {
            write(" ORDER BY ")
            renderOrderTerms(orderBy)
        }
        if let limit {
            write(" LIMIT ")
            bind(.int(Int64(limit)))
        }
    }

    private mutating func renderTarget(schema: String?, table: String, alias: String?) {
        if let schema { identifier(schema); write(".") }
        identifier(table)
        if let alias { write(" AS "); identifier(alias) }
    }
}

// MARK: - UPDATE and DELETE

extension SQLRenderer {
    public mutating func renderUpdate(_ core: SQLUpdateCore) {
        write("UPDATE ")
        renderTarget(schema: core.schema, table: core.table, alias: core.alias)
        write(" SET ")
        renderAssignments(core.assignments)
        if !core.predicates.isEmpty {
            write(" WHERE ")
            renderConjunction(core.predicates)
        }
        renderWriteTail(core.orderBy, core.limit)
        renderReturning(core.returning)
        renderTrailing(core.trailing)
    }

    public mutating func renderDelete(_ core: SQLDeleteCore) {
        write("DELETE FROM ")
        renderTarget(schema: core.schema, table: core.table, alias: core.alias)
        if !core.predicates.isEmpty {
            write(" WHERE ")
            renderConjunction(core.predicates)
        }
        renderWriteTail(core.orderBy, core.limit)
        renderReturning(core.returning)
        renderTrailing(core.trailing)
    }
}
