import SwizzleCore
import SwizzleSQLite
import Testing
@testable import SwizzleGenerate

@Suite("Schema generation")
struct SchemaGenerationTests {

    static func migrated() async throws -> SQLiteConnection {
        let connection = try SQLiteConnection.inMemory()
        _ = try await connection.query(
            """
            CREATE TABLE user_accounts (
                id         INTEGER PRIMARY KEY,
                email      VARCHAR(255) NOT NULL,
                nickname   TEXT,
                balance    DECIMAL(10,2) NOT NULL,
                is_active  BOOLEAN NOT NULL DEFAULT 1,
                created_at TIMESTAMP,
                avatar     BLOB
            )
            """
        )
        return connection
    }

    func generate(_ connection: SQLiteConnection) async throws -> String {
        let schema = try await SQLiteIntrospector(connection).schema()
        return SchemaEmitter(options: .init(dialect: "sqlite")).emit(schema)
    }

    @Test("declarations mirror the SQL types they were read from")
    func declarationsMirrorSQLTypes() async throws {
        let connection = try await Self.migrated()
        defer { connection.close() }
        let source = try await generate(connection)

        #expect(source.contains(#"public static let tableName = "user_accounts""#))
        #expect(source.contains("public struct UserAccounts: SQLTable"))

        // The length and precision are the point: they come from the server, so
        // they cannot drift from the migration the way a hand-written one can.
        #expect(source.contains(#"var email: SQLColumn<String> { varchar("email", 255) }"#))
        #expect(source.contains(#"var balance: SQLColumn<String> { decimal("balance", 10, 2) }"#))
        #expect(source.contains(#"var isActive: SQLColumn<Bool> { boolean("is_active") }"#))
        #expect(source.contains(#"var avatar: SQLColumn<[UInt8]?> { blob("avatar") }"#))

        // Nullability is the Swift optional, and only the nullable ones get it.
        #expect(source.contains("var nickname: SQLColumn<String?>"))
        #expect(source.contains("var createdAt: SQLColumn<String?>"))
        #expect(!source.contains("var email: SQLColumn<String?>"))
    }

    /// `DECIMAL` must never become `Double`. The cents are the whole reason the
    /// type exists, and this is the contract the hand-written declarations
    /// already document.
    @Test("exact numerics stay text")
    func decimalStaysText() async throws {
        let connection = try await Self.migrated()
        defer { connection.close() }
        let source = try await generate(connection)
        #expect(source.contains("var balance: SQLColumn<String>"))
        #expect(!source.contains("var balance: SQLColumn<Double>"))
    }

    /// `id INTEGER PRIMARY KEY` is the rowid alias. SQLite truthfully reports it
    /// nullable — inserting NULL means "assign one" — and taking that at face
    /// value made every primary key an `Int64?`, which is the unwrap-everything
    /// failure that makes generated code unpleasant enough to abandon.
    @Test("an auto-increment primary key is not optional")
    func autoIncrementKeyIsNotOptional() async throws {
        let connection = try await Self.migrated()
        defer { connection.close() }
        let source = try await generate(connection)
        #expect(source.contains(#"var id: SQLColumn<Int64> { int("id") }"#))
        #expect(!source.contains("var id: SQLColumn<Int64?>"))
    }

    /// Regeneration has to be byte-stable, or `--verify` reports drift that is
    /// only dictionary ordering.
    @Test("generating twice produces identical bytes")
    func generationIsDeterministic() async throws {
        let connection = try await Self.migrated()
        defer { connection.close() }
        _ = try await connection.query("CREATE TABLE zzz (a INTEGER)")
        _ = try await connection.query("CREATE TABLE aaa (b INTEGER)")

        let first = try await generate(connection)
        let second = try await generate(connection)
        #expect(first == second)

        // Sorted, so a server that returns tables in a different order does not
        // rewrite the file.
        let aaa = try #require(first.range(of: "struct Aaa"))
        let zzz = try #require(first.range(of: "struct Zzz"))
        #expect(aaa.lowerBound < zzz.lowerBound)
    }

    @Test("generated files say they are generated")
    func generatedFilesAreMarked() async throws {
        let connection = try await Self.migrated()
        defer { connection.close() }
        let source = try await generate(connection)
        #expect(source.hasPrefix("// Generated by swizzle. Do not edit."))
        #expect(source.contains("swizzle generate schema"))
    }
}

@Suite("Column type names")
struct ColumnTypeNameTests {

    /// The same word means different widths on different engines, which is why
    /// the emitter has to be told which one it read from.
    @Test("INTEGER is 64-bit on SQLite and 32-bit everywhere else")
    func integerWidthIsDialectSpecific() {
        #expect(ColumnTypeName.parse("INTEGER", dialect: "sqlite").swiftType == .int64)
        #expect(ColumnTypeName.parse("integer", dialect: "postgres").swiftType == .int32)
        #expect(ColumnTypeName.parse("int", dialect: "mysql").swiftType == .int32)

        // SQLite stores every integral column as a 64-bit value, so the narrow
        // names do not mean what they say there either.
        #expect(ColumnTypeName.parse("SMALLINT", dialect: "sqlite").swiftType == .int64)
        #expect(ColumnTypeName.parse("smallint", dialect: "postgres").swiftType == .int16)
    }

    /// `BIGINT UNSIGNED` does not fit `Int64`. The driver already hands large
    /// values over as text rather than wrapping; `UInt64` is what accepts both.
    @Test("unsigned bigint widens rather than wrapping")
    func unsignedBigIntWidens() {
        #expect(ColumnTypeName.parse("bigint unsigned", dialect: "mysql").swiftType == .uint64)
        #expect(ColumnTypeName.parse("bigint", dialect: "mysql").swiftType == .int64)
    }

    @Test("arguments are recovered and fed to the constructor")
    func argumentsAreRecovered() {
        let varchar = ColumnTypeName.parse("varchar(64)")
        #expect(varchar.constructorCall(named: "email") == #"varchar("email", 64)"#)

        let decimal = ColumnTypeName.parse("decimal(12,4)")
        #expect(decimal.constructorCall(named: "total") == #"decimal("total", 12, 4)"#)

        // A missing length falls back rather than emitting broken source.
        #expect(ColumnTypeName.parse("varchar").constructorCall(named: "x") == #"varchar("x", 255)"#)
    }

    @Test("each engine's spelling reaches the right constructor")
    func spellingsMapAcrossEngines() {
        #expect(ColumnTypeName.parse("character varying(30)").constructorCall(named: "c")
            == #"varchar("c", 30)"#)
        #expect(ColumnTypeName.parse("timestamp with time zone").constructorCall(named: "t")
            == #"timestamptz("t")"#)
        #expect(ColumnTypeName.parse("bytea").constructorCall(named: "b") == #"bytea("b")"#)
        #expect(ColumnTypeName.parse("longblob").constructorCall(named: "b") == #"blob("b")"#)
        #expect(ColumnTypeName.parse("jsonb").constructorCall(named: "j") == #"jsonb("j")"#)
    }

    /// A type nothing models must still produce usable source, with the real name
    /// visible, rather than a guess.
    @Test("an unmodelled type falls back to the general constructor")
    func unknownTypesFallBack() {
        let geometry = ColumnTypeName.parse("geometry")
        #expect(geometry.constructorCall(named: "shape") == #"column("shape")"#)
        #expect(geometry.swiftType == .dynamic)
    }

    /// `enum` is a Swift keyword, and the constructor is spelled with backticks.
    @Test("a keyword constructor is escaped")
    func keywordConstructorIsEscaped() {
        #expect(ColumnTypeName.parse("enum").constructorCall(named: "kind") == "`enum`(\"kind\")")
    }
}

@Suite("Swift names")
struct SwiftNameTests {

    @Test("snake case becomes Swift case")
    func snakeCaseConverts() {
        #expect(SwiftNames.typeName("user_accounts") == "UserAccounts")
        #expect(SwiftNames.memberName("created_at") == "createdAt")
        #expect(SwiftNames.memberName("is_active") == "isActive")
    }

    /// `Id` reads as generated; `ID` reads as Swift.
    @Test("initialisms are shouted the way Swift shouts them")
    func initialismsAreShouted() {
        #expect(SwiftNames.memberName("user_id") == "userID")
        #expect(SwiftNames.memberName("id") == "id")
        #expect(SwiftNames.typeName("api_keys") == "APIKeys")
        #expect(SwiftNames.memberName("avatar_url") == "avatarURL")
    }

    @Test("names that are already camel case survive")
    func camelCaseSurvives() {
        #expect(SwiftNames.memberName("createdAt") == "createdAt")
        #expect(SwiftNames.typeName("UserAccounts") == "UserAccounts")
    }

    /// Columns really are called things like `class` and `2fa_enabled`.
    @Test("keywords and leading digits are made legal")
    func illegalNamesAreMadeLegal() {
        #expect(SwiftNames.memberName("class") == "`class`")
        #expect(SwiftNames.memberName("default") == "`default`")
        #expect(SwiftNames.memberName("2fa_enabled") == "_2faEnabled")
        #expect(SwiftNames.typeName("order") == "Order")
    }
}
