import Crypto
import Foundation
import Testing
@testable import SwizzleMySQL

/// Known-answer vectors for `client_ed25519`, **generated by libsodium**.
///
/// These were captured from libsodium-as-a-package-dependency, survived a period
/// when the arithmetic was pure Swift, and now check libsodium-as-vendored-C.
/// That history is the point: the same eight vectors have held across three
/// different implementations of the same maths, so they are a genuine anchor
/// rather than a snapshot of whatever the code happened to do.
@Suite("ed25519 known-answer vectors")
struct Ed25519VectorTests {

    struct Vector {
        let password: String
        let scramble: String
        let publicKey: String
        let signature: String
    }

    static func hex(_ text: String) -> [UInt8] {
        var out = [UInt8]()
        var index = text.startIndex
        while index < text.endIndex {
            let next = text.index(index, offsetBy: 2)
            out.append(UInt8(text[index..<next], radix: 16)!)
            index = next
        }
        return out
    }

    static let vectors: [Vector] = [
        Vector(
            password: "ed25519pass",
            scramble: "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
            publicKey: "fc93264001ee21a3ac54d2b2bad4cdb5c24e294f49b396edf0bc11406472601f",
            signature: "c97a7847aee4b95e1beea4b89feded164db8d1b436a49527bab4de415ea0efbd"
                + "b1434530069c51ab83dc01d7c954e6b826f1c55cc05743e147909bb53e75620d"
        ),
        Vector(
            password: "ed25519pass",
            scramble: "abababababababababababababababababababababababababababababababab",
            publicKey: "fc93264001ee21a3ac54d2b2bad4cdb5c24e294f49b396edf0bc11406472601f",
            signature: "625084500e56818919fa6cc007b61cba4a564d378049da6fc3772d7c7d06cbbe"
                + "576de09af8fe005c0931ffa31aa40c0248565f71a9c2af1fc7026b0c82c79606"
        ),
        // Empty password: an empty response, as with every other plugin. The
        // public key is still well-defined — SHA512("") is a perfectly good
        // expansion — which is why it is pinned rather than skipped.
        Vector(
            password: "",
            scramble: "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
            publicKey: "e0b1fe74117e1b95b608a4f221df314774b20ea66842350d515371c7c6966c6e",
            signature: ""
        ),
        // An all-zero scramble, which a lazy implementation might special-case.
        Vector(
            password: "a",
            scramble: "0000000000000000000000000000000000000000000000000000000000000000",
            publicKey: "1af4668bdba78058c90fdb0a8daabf4f708bd4b98ed822e9cf9238da09c1ec48",
            signature: "716912c3806eb7c21044be597becddc3e909ee7b21f32dd294b4693454964a2d"
                + "c952a51747bcc2be156376e9588fe7b252019f7e5f94d3859bf661f4378ce103"
        ),
        Vector(
            password: "correct horse battery staple",
            scramble: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            publicKey: "d7eb98a8b4bb27fc975110974792e33e5d136433f96e48155ead4aabd68278be",
            signature: "758e28ef3e936b5e7eeea2495da8deac954833f290e012bc71f5f1699f4c827d"
                + "4678dec4f22925bbe5385e49be1d102d395ca13a3c91055f40d2f35cdc265900"
        ),
        // Non-ASCII: derivation runs over raw UTF-8 with no normalisation.
        Vector(
            password: "pÄss‑wörd",
            scramble: "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
            publicKey: "3156aabe07490dcbb34f4b423648f637b2b0c1abaa484c2698d0d28deca49d0f",
            signature: "074ee266cf7971f2c8fa083c6a6e74b3d317499d71cb16a2708e1571c523bb8f"
                + "6f053428eb7708b0dd69b749024d9afeee27f4ca800d14e1044284ba0af2fc04"
        ),
        Vector(
            password: "x",
            scramble: "fefdfcfbfaf9f8f7f6f5f4f3f2f1f0efeeedecebeae9e8e7e6e5e4e3e2e1e0df",
            publicKey: "1afd8923c127bf67dde581a89d9d3cdad5f75005bec8962574e963e11d5b7cae",
            signature: "dd92998d320e65c3dc8222ace431e890abaab612093f07d9bed9688908eee1d9"
                + "230a83553f3fa7cc497ef4e00480fcdca3955f97e172f9ca237543a8d7b3ca01"
        ),
        // A password far longer than one SHA-512 block.
        Vector(
            password: String(repeating: "long", count: 64),
            scramble: "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
            publicKey: "edb9a69ff7824ed260520eec9eb4705a95fc78aab439b8d4f90674e34a5d1bcb",
            signature: "3e038ee2a28c952f2ca4e72a52c829dec8334f32f422df9dbc84273cdba5e7f9"
                + "0374748c0c3e3a58d14dd0043d3bbfd58cc5adae633e1581fd010a3bfe6a7b08"
        ),
    ]

    @Test(arguments: vectors.indices)
    func publicKeyMatchesLibsodium(index: Int) throws {
        let vector = Self.vectors[index]
        let derived = try MySQLEd25519.publicKey(password: vector.password)
        #expect(derived == Self.hex(vector.publicKey), "password: \(vector.password.prefix(24))")
    }

    @Test(arguments: vectors.indices)
    func signatureMatchesLibsodium(index: Int) throws {
        let vector = Self.vectors[index]
        let signature = try MySQLEd25519.sign(
            password: vector.password, scramble: Self.hex(vector.scramble)
        )
        #expect(signature == Self.hex(vector.signature))
    }

    /// Independent of the frozen values: swift-crypto must accept every
    /// signature under the key we derived. This is what would catch an error
    /// that somehow made it into both the vectors and the implementation.
    @Test(arguments: vectors.indices)
    func signaturesVerifyUnderSwiftCrypto(index: Int) throws {
        let vector = Self.vectors[index]
        guard !vector.password.isEmpty else { return }

        let scramble = Self.hex(vector.scramble)
        let signature = try MySQLEd25519.sign(password: vector.password, scramble: scramble)
        let key = try Curve25519.Signing.PublicKey(
            rawRepresentation: MySQLEd25519.publicKey(password: vector.password)
        )
        #expect(key.isValidSignature(Data(signature), for: Data(scramble)))
    }

    /// The one place the two implementations deliberately differ, pinned from
    /// both sides so it stays a recorded decision.
    ///
    /// libsodium **refuses** a zero scalar — `crypto_scalarmult_ed25519_base_noclamp`
    /// returns −1 rather than a point, because it rejects identity and
    /// small-order outputs. The Swift oracle returns the mathematically correct
    /// identity encoding (`01` followed by 31 zero bytes).
    ///
    /// Both are defensible and neither is reachable here: every scalar comes out
    /// of SHA-512, and the secret is clamped so bit 254 is always set. Vendoring
    /// the C restored libsodium's stricter behaviour, which is the safer of the
    /// two — a degenerate point now surfaces as an error instead of a silently
    /// useless signature.
    @Test func zeroScalarIsRefusedByLibsodium() {
        #expect(throws: (any Error).self) {
            _ = try MySQLEd25519.scalarMultiplyBase([UInt8](repeating: 0, count: 32))
        }
    }

    /// And the oracle's answer, so the divergence is documented rather than
    /// merely asserted on one side.
    @Test func theSwiftOracleReturnsTheIdentityForAZeroScalar() {
        var expected = [UInt8](repeating: 0, count: 32)
        expected[0] = 1
        #expect(Ed25519Core.scalarMultiplyBase([UInt8](repeating: 0, count: 32)) == expected)
    }
}
